# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'MemTrick.sln'
  buildPlatform: 'Mixed Platform'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: 'Debug'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: 'Release'

- task: VSTest@2
  condition: always()
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: | 
      **/bin/x86/Debug/**/MemTrick.Test.CLR.x86.dll
    testRunTitle: 'CLR.x86/Debug'
    platform: 'x86'
    configuration: 'Debug'
- task: VSTest@2
  condition: always()
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: | 
      **/bin/x64/Debug/**/MemTrick.Test.CLR.x64.dll
    testRunTitle: 'CLR.x64/Debug'
    platform: 'x64'
    configuration: 'Debug'
- task: VSTest@2
  condition: always()
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: | 
      **/bin/x64/Debug/**/MemTrick.Test.CoreCLR2.x64.dll
    testRunTitle: 'CoreCLR2.x64/Debug'
    platform: 'x64'
    configuration: 'Debug'

- task: VSTest@2
  condition: always()
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: | 
      **/bin/x86/Release/**/MemTrick.Test.CLR.x86.dll
    testRunTitle: 'CLR.x86/Release'
    platform: 'x86'
    configuration: 'Release'
- task: VSTest@2
  condition: always()
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: | 
      **/bin/x64/Release/**/MemTrick.Test.CLR.x64.dll
    testRunTitle: 'CLR.x64/Release'
    platform: 'x64'
    configuration: 'Release'
- task: VSTest@2
  condition: always()
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: | 
      **/bin/x64/Release/**/MemTrick.Test.CoreCLR2.x64.dll
    testRunTitle: 'CoreCLR2.x64/Release'
    platform: 'x64'
    configuration: 'Release'

